//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentOfCar.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarSupplier
    {
        public int Id { get; set; }
        public Nullable<int> CarId { get; set; }
        public Nullable<int> ReceiptOfCatId { get; set; }
        public Nullable<int> Count { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual ReceiptOfCar ReceiptOfCar { get; set; }
    }
}
