//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentOfCar.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiptOfCar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReceiptOfCar()
        {
            this.CarSupplier = new HashSet<CarSupplier>();
        }
    
        public int Id { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> SupplierId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarSupplier> CarSupplier { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
